version: '3.8'
services:
  web:
    build: ./client 
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  api:
    build: ./server 
    ports:
      - 3001:3001 
    volumes:
      - ./server:/app
